import { ActivityIndicator, Alert, Pressable, Text, View } from 'react-native';
import { useEffect, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Header, Screen } from '../../../components/UI';
import { colors } from '../../../constants/theme';
import { useAppStore } from '../../../store/appStore';
import { getCustomerAddresses, type CustomerAddress } from '../../../services/customerAddresses';
import { getProducts, type Product } from '../../../services/products/productService';
import { getActiveSubscriptionPlans, getCustomerSubscriptions, isSubscriptionEligible, prettySubscriptionStatus, type CustomerSubscription, type SubscriptionPlan } from '../../../services/subscriptions/subscriptionService';

const money=(n:number)=>`₹${n.toLocaleString('en-IN')}`;
const addressText=(a:CustomerAddress)=>[a.addressLine1,a.addressLine2,a.landmark,a.city,a.state,a.pincode].filter(Boolean).join(', ');

export default function Subscriptions(){
 const mobile=useAppStore(s=>s.mobile); const params=useLocalSearchParams<{productId?:string}>();
 const [plans,setPlans]=useState<SubscriptionPlan[]>([]); const [subs,setSubs]=useState<CustomerSubscription[]>([]); const [products,setProducts]=useState<Product[]>([]); const [addresses,setAddresses]=useState<CustomerAddress[]>([]); const [loading,setLoading]=useState(true); const [selectedPlan,setSelectedPlan]=useState(''); const [selectedProduct,setSelectedProduct]=useState('');
 useEffect(()=>{let alive=true;if(!mobile){router.replace('/(customer)/auth/login');return()=>{alive=false}};(async()=>{try{const [p,s,pr,a]=await Promise.all([getActiveSubscriptionPlans(),getCustomerSubscriptions(mobile),getProducts(),getCustomerAddresses(mobile)]);if(!alive)return;setPlans(p);setSubs(s);setProducts(pr.products.filter(isSubscriptionEligible));setAddresses(a);if(params.productId&&pr.products.some(x=>x.id===params.productId&&isSubscriptionEligible(x)))setSelectedProduct(params.productId);else setSelectedProduct(pr.products.find(isSubscriptionEligible)?.id||'');}catch(e){if(alive)Alert.alert('Unable to load subscriptions',e instanceof Error?e.message:'Please try again.')}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[mobile,params.productId]);
 const active=subs.find(s=>s.status==='active');
 return <Screen><Header title="Subscriptions" onBack={()=>router.back()}/>{loading?<View style={{paddingVertical:60,alignItems:'center'}}><ActivityIndicator size="large" color={colors.green}/><Text style={{color:colors.inkSoft,marginTop:12}}>Loading subscriptions…</Text></View>:<>
 <View style={{backgroundColor:'#fff',borderRadius:15,borderWidth:1,borderColor:colors.lineSoft,padding:16,marginBottom:14}}><Text style={{fontSize:18,fontWeight:'900',color:colors.ink}}>My Subscription</Text>{active?<><Text style={{fontSize:17,fontWeight:'900',color:colors.greenDark,marginTop:12}}>{active.productName||'Subscription'}</Text><Text style={{color:colors.inkSoft,marginTop:5}}>{active.sellingOptionLabel||'Pack'} × {active.quantity||1} · {active.frequency||''} · Saturday delivery</Text><View style={{flexDirection:'row',gap:8,marginTop:14}}>{[['Status',prettySubscriptionStatus(active.status)],['Deliveries',String(active.totalDeliveries??'—')],['Remaining',String(active.remainingDeliveries??'—')]].map(x=><View key={x[0]} style={{flex:1,backgroundColor:colors.greenTint,borderRadius:10,padding:10}}><Text style={{fontSize:10,color:colors.inkSoft,fontWeight:'800'}}>{x[0]}</Text><Text style={{fontSize:14,color:colors.greenDark,fontWeight:'900',marginTop:3}}>{x[1]}</Text></View>)}</View><Text style={{color:colors.inkSoft,marginTop:12}}>Next delivery: <Text style={{fontWeight:'900',color:colors.ink}}>{active.nextDeliveryDate||'—'}</Text></Text></>:<Text style={{color:colors.inkSoft,marginTop:8}}>No active subscription found.</Text>}</View>
 <Text style={{fontSize:18,fontWeight:'900',color:colors.ink,marginBottom:10}}>Available plans</Text>{plans.length?plans.map(p=><Pressable key={p.id} onPress={()=>setSelectedPlan(p.id)} style={{backgroundColor:'#fff',borderRadius:14,borderWidth:1,borderColor:selectedPlan===p.id?colors.green:colors.lineSoft,padding:15,marginBottom:10}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View><Text style={{fontSize:16,fontWeight:'900',color:colors.ink}}>{p.name}</Text><Text style={{color:colors.inkSoft,marginTop:4}}>{p.frequency}{p.deliveriesPerTerm?` · ${p.deliveriesPerTerm} deliveries`:''} · Saturday</Text></View><Text style={{fontSize:18,fontWeight:'900',color:colors.greenDark}}>{money(p.price)}</Text></View>{selectedPlan===p.id&&<Text style={{color:colors.greenDark,fontWeight:'800',marginTop:9}}>Selected</Text>}</Pressable>):<Text style={{color:colors.inkSoft}}>No active subscription plans are available.</Text>}
 <Text style={{fontSize:18,fontWeight:'900',color:colors.ink,marginTop:10,marginBottom:10}}>Subscription product</Text>{products.length?products.map(p=><Pressable key={p.id} onPress={()=>setSelectedProduct(p.id)} style={{backgroundColor:'#fff',borderRadius:14,borderWidth:1,borderColor:selectedProduct===p.id?colors.green:colors.lineSoft,padding:15,marginBottom:10}}><Text style={{fontSize:16,fontWeight:'900',color:colors.ink}}>{p.name}</Text><Text style={{color:colors.inkSoft,marginTop:4}}>{p.defaultWeight} · {money(p.price)} per pack</Text>{selectedProduct===p.id&&<Text style={{color:colors.greenDark,fontWeight:'800',marginTop:8}}>Selected for subscription</Text>}</Pressable>):<Text style={{color:colors.inkSoft}}>No salable products are currently eligible for subscription.</Text>}
 <View style={{backgroundColor:colors.orangeTint,borderRadius:14,padding:15,marginTop:6}}><Text style={{fontWeight:'900',color:colors.brown}}>Subscription setup</Text><Text style={{color:colors.inkSoft,marginTop:6,lineHeight:20}}>Your saved delivery address: {addresses[0]?addressText(addresses[0]):'Add an address first.'}</Text><Text style={{color:colors.inkSoft,marginTop:6,lineHeight:20}}>The website currently creates and changes subscriptions through its trusted server flow. Mobile will not write subscription status or financial data directly from the client.</Text></View>
 </>}</Screen>
}
